language: none
build:
  ci:
    - echo "In CI"

resources:

  - name: prgitRepo
    type: gitRepo
    integration: github
    versionTemplate:
      sourceName: ambarish2012/pr-runsh-sample
      # Remove branch below if you want PRs to be triggered for all branches.
      # If you want to trigger for some branches but not others, use branches tag
      # as documented here: http://docs.shippable.com/platform/workflow/resource/gitrepo/#gitrepo
      branch: master
      buildOnCommit: false 
      buildOnPullRequest: true

jobs:

  - name: runPrTests
    type: runSh
    allowPublicAccess: true
    steps:
      - IN: prgitRepo
      - TASK:
        - script:
            # cd into the directory where the repository is checked out
            - pushd $(shipctl get_resource_state prgitRepo)
            - ./runtests.sh
            
