language: none
build:
  ci:
    - echo "In CI"

resources:

  - name: prgitRepo
    type: gitRepo
    integration: github
    versionTemplate:
      sourceName: ambarish2012/pr-runsh-sample
      branch: master
      buildOnCommit: false 
      buildOnPullRequest: true

jobs:

  - name: runPrTests
    type: runSh
    steps:
      - IN: prgitRepo
      - TASK:
        - script: echo "triggered for PR requests"
